### ISSUE TITLE
Osmose issues lack detail

### ISSUE THREAD

**Issue by blackboxlogic** [MarcusWolschon/osmeditor4android#928]
## Vespucci Version
Vespucci 13.0.2
Flavor: current
Maximum avaliable memory 536870912
Total memory used 42273504
Tile Cache BING usage Size 66846720 of maximum 67108864 #entries 255
State file size 398246 last changed 2019-06-19 11:30:57
Bug state file size 18968 last changed 2019-06-19 11:30:57
Relations (current/API): 17/0
Ways (current/API): 452/0
Nodes (current/Waynodes/API): 5597/6285/0
Available location providers
passive enabled true
gps enabled true
network enabled true

## Download source
f-droid

## Device (Manufacturer and Model)
Google pixel 3

## Android Version 
9

## Behaviour/Symptoms
Clicking on yellow bug icons on the map shows a dialog with information related to an Osmose issue. But there is no description or details about the Osmose issue. User (me) doesn't know what is wrong or how to fix the mapping issue.
![Screenshot](https://user-images.githubusercontent.com/31355456/59762246-d3d75400-9264-11e9-9ac4-7b38b077aa72.png)

## Expected Behaviour
When the map shows an Osmose issue, the dialog should show a description or details about the problem so the user can address the Osmose issue.

## How to recreate
* Browse map for yellow bug icon
* Tap icon for dialog about Osmose issue
* Read dialog, be confused

## Crash dump submitted (no or yes + date)
No crash

## Any other potentially relevant information
Nope

**Comment by blackboxlogic** [comment]
I acknowledge this could be "user error". I'm new, please be gentle.

**Comment by simonpoole** [comment]
Thanks for the report. Definitely not user error, but fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/751c240e5af61d29a89949941400fd84106db904

a couple of days back (seems as if Osmose slightly changed how it behaves).

**Comment by simonpoole** [comment]
PS: could you upgrade to 13.0.4 aka the current release as there is a Relation related issue in previous releases?

**Comment by blackboxlogic** [comment]
_F-Droid_ and _Google Play_ both show 13.0.2 as the current version. I see the google play has an option to "Join the Beta". Will that get me to 13.0.4 as you suggest?

**Comment by simonpoole** [comment]
The beta is 13.1.0 which you are naturally welcome to test. F-droid has had 13.0.4 for quite while as in more than a month maybe you need to refresh the F-Droid data.

Am 19. Juni 2019 15:37:03 MESZ schrieb blackboxlogic <notifications@github.com>:
>_F-Droid_ and _Google Play_ both show 13.0.2 as the current version. I
>see the google play has an option to "Join the Beta". Will that get me
>to 13.0.4 as you suggest?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarcusWolschon/osmeditor4android/issues/928#issuecomment-503564016

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by blackboxlogic** [comment]
I'm on 13.0.4 now, and still seeing most Osmose issues don't display any description. Some do have descriptions.


Vespucci 13.0.4
Flavor: current
Maximum avaliable memory 536870912
Total memory used 24687285
Tile Cache MAPNIK usage Size 66846720 of maximum 67108864 #entries 255
State file size 466669 last changed 2019-06-19 16:14:34
Bug state file size 12685 last changed 2019-06-19 16:14:34
Relations (current/API): 17/0
Ways (current/API): 535/0
Nodes (current/Waynodes/API): 6731/7556/0
Available location providers
passive enabled true
gps enabled true
network enabled true

**Comment by simonpoole** [comment]
That's a misunderstanding,  13.04 is s month old, the fix for the Osmose Problem one week. A 13.0.5 update is in the works and will contain the fix


Am 19. Juni 2019 18:20:47 MESZ schrieb blackboxlogic <notifications@github.com>:
>I'm on 13.0.4 now, and still seeing most Osmose issues don't display
>any description. Some do have descriptions.
>
>
>Vespucci 13.0.4
>Flavor: current
>Maximum avaliable memory 536870912
>Total memory used 24687285
>Tile Cache MAPNIK usage Size 66846720 of maximum 67108864 #entries 255
>State file size 466669 last changed 2019-06-19 16:14:34
>Bug state file size 12685 last changed 2019-06-19 16:14:34
>Relations (current/API): 17/0
>Ways (current/API): 535/0
>Nodes (current/Waynodes/API): 6731/7556/0
>Available location providers
>passive enabled true
>gps enabled true
>network enabled true
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarcusWolschon/osmeditor4android/issues/928#issuecomment-503630905

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by blackboxlogic** [comment]
Oh! That's clear now. Thank you for your work.

**Comment by RedEye2063** [comment]
I have version 13.1.8 and there seem to be more Osmose Issues without detailed information. I compared the notifications with the Osmose web frontend. It seems that Vespucci only shows the title, but not the subtitle. The subtitle is essential though for understanding some of the issues. It would be great if Vespucci showed the subtitles, too.

**Comment by simonpoole** [comment]
@RedEye2063 could you provide a link to a concrete Osmose issue that shows the issue?

**Comment by RedEye2063** [comment]
Not every issue has a subtitle, but here are two examples with existing subtitles:
http://osmose.openstreetmap.fr/en/error/33330527944
http://osmose.openstreetmap.fr/en/error/33330532766

I also noticed something interesting: The subtitle is acually shown in the selection menu (when you tap a place with multiple objects close to each other). But when you select an issue and the issue window pops up, the subtitle is not there.

**Comment by simonpoole** [comment]
Unfortunately those issues are already closed. A screenshot would be helpful. I suspect that the issue must be error specific, as all the issues around here work as intended.

**Comment by RedEye2063** [comment]
That's odd. They were both open yesterday. Anyway here's another one: http://osmose.openstreetmap.fr/en/error/33385956106

**Screenshot from Osmose:**
![Screenshot_20191004-230544_Chrome](https://user-images.githubusercontent.com/40234965/66243609-12522b00-e6fd-11e9-9494-1a3c4aadce3b.jpg)

**Same issue in Vespucci:**
![Screenshot_20191004-232228_Vespucci](https://user-images.githubusercontent.com/40234965/66243835-fbf89f00-e6fd-11e9-8db3-1173461cbb20.jpg)
